FROM python:3.12.0-slim-bookworm

# Set environment variables to avoid Python buffering and write bytecode
ENV PYTHONBUFFERED 1
ENV PYTHONWRITEBYTECODE 1
ENV APP=/app

# Change the working directory to /app
WORKDIR $APP

# Copy the requirements.txt file and install dependencies
COPY requirements.txt $APP
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# Copy the rest of the application files
COPY . $APP

# Expose the port that the application will run on
EXPOSE 8000

# Make entrypoint.sh executable
RUN chmod +x /app/entrypoint.sh

# Define the entry point and default command to run the application
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]
CMD ["gunicorn", "--bind", ":8000", "--workers", "3", "djangoproj.wsgi"]
